version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.6.4
  - dependency-name: ember-cli
    versions:
    - 3.24.0
    - 3.25.0
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
  commit-message:
    prefix: ""
